#!/usr/bin/env bash
#
# This file is part of the kiagnose project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2023 Red Hat, Inc.
#

set -e

# Disable unnecessary services
disable_services() {
  local service_list=("NetworkManager-wait-online" "sshd" "irqbalance")
  for service in "${service_list[@]}"; do
    systemctl disable "$service"
  done
}

# Install required packages
install_packages() {
  dnf --enablerepo=rt install -y tuned-profiles-realtime
  dnf --enablerepo=nfv install -y tuned-profiles-nfv-guest
}

# Disable swap
disable_swap() {
  swapoff -a
  sed -i '/swap/s/^/#/' /etc/fstab
}

# Create and enable the boot checkup service
setup_boot_service() {
  local service_name="realtime-checkup-boot.service"
  local checkup_boot_script_full_path="/usr/bin/realtime-checkup-boot.sh"
  local checkup_boot_service_full_path="/usr/lib/systemd/system/$service_name"
  local checkup_boot_ready_marker_full_path="/var/realtime-checkup-image-ready-marker"

  setup_checkup_boot_script "$checkup_boot_script_full_path"

  cat <<EOF > "$checkup_boot_service_full_path"
[Unit]
Description=Checkup Boot Script
Before=qemu-guest-agent.service
ConditionPathExists=!$checkup_boot_ready_marker_full_path
[Service]
Type=oneshot
ExecStart=$checkup_boot_script_full_path $checkup_boot_ready_marker_full_path
Restart=no
User=root
Group=root
[Install]
WantedBy=multi-user.target
Wants=first-boot-complete.target
EOF

  systemctl enable "$checkup_boot_service_full_path"
  systemctl start "$checkup_boot_service_full_path"
}

setup_checkup_boot_script() {
  local checkup_boot_script_full_path=$1
cat <<'EOF' > "$checkup_boot_script_full_path"
#!/usr/bin/env bash
#
# This file is part of the kiagnose project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2024 Red Hat, Inc.
#

set -x

checkup_boot_ready_marker_full_path=$1
checkup_tuned_adm_set_marker_full_path="/var/realtime-checkup-tuned-adm-set-marker"

if systemctl --type swap list-units | grep -q '.swap'; then
  systemctl mask "$(systemctl --type swap list-units | grep '.swap' | awk '{print $1}')"
fi

if [ ! -f "$checkup_tuned_adm_set_marker_full_path" ]; then
  tuned_conf="/etc/tuned/realtime-virtual-guest-variables.conf"
  echo "isolated_cores=2-3" > "$tuned_conf"
  echo "isolate_managed_irq=Y" >> "$tuned_conf"
  tuned-adm profile realtime-virtual-guest
  touch $checkup_tuned_adm_set_marker_full_path
  reboot
  exit 0
fi

touch $checkup_boot_ready_marker_full_path
EOF

  chmod +x "$checkup_boot_script_full_path"
}

disable_services
install_packages
disable_swap
setup_boot_service
