#!/usr/bin/env bash
#
# This file is part of the kiagnose project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2023 Red Hat, Inc.
#

set -e

# Disable unnecessary services
disable_services() {
  local service_list=("NetworkManager-wait-online" "sshd" "irqbalance")
  for service in "${service_list[@]}"; do
    systemctl disable "$service"
  done
}

# Install required packages
install_packages() {
  dnf --enablerepo=rt install -y kernel-rt tuned-profiles-realtime
  dnf --enablerepo=nfv install -y tuned-profiles-nfv-guest
}

# Disable swap
disable_swap() {
  swapoff -a
  sed -i '/swap/s/^/#/' /etc/fstab
}

# Enable guest-exec on the qemu-guest-agent configuration
enable_guest_exec() {
  sed -i '/^BLACKLIST_RPC=/ { s/guest-exec-status//; s/guest-exec//g }' /etc/sysconfig/qemu-ga
  sed -i '/^BLACKLIST_RPC=/ { s/,\+/,/g; s/^,\|,$//g }' /etc/sysconfig/qemu-ga
}

disable_bracketed_paste() {
  echo "set enable-bracketed-paste off" >> /root/.inputrc
}

disable_services
install_packages
disable_swap
enable_guest_exec
disable_bracketed_paste
